---
title: "მესამე ლაბორატორია"
output: html_notebook
---

```{r}
setwd("D:\\Dropbox\\My projects\\Courses\\ST_R\\website\\meetings\\m3\\lab\\key")

library(haven)
library(dplyr)

ndidec <- read_dta("NDI_2017_Dec_25_12_17_public.dta")

```

```{r}
table(ndidec$PARTYSUPP1)
prop.table(table(ndidec$PARTYSUPP1))
na.omit(count(x = ndidec, SETTYPE, wt = WTIND))
settype.table <- na.omit(count(x = ndidec, SETTYPE, wt = WTIND))
settype.table$proportion <- settype.table$n/sum(settype.table$n)
print(settype.table)
```

```{r}
ndidec$party <- 5
ndidec$party[ndidec$PARTYSUPP1==8] <- 1
ndidec$party[ndidec$PARTYSUPP1==6] <- 2
ndidec$party[ndidec$PARTYSUPP1==-1 | ndidec$PARTYSUPP1==-2] <- 3
ndidec$party[ndidec$PARTYSUPP1==26] <- 4
table(ndidec$party)

ndidec$imedi <- ndidec$TRUIMEDI
ndidec$imedi[ndidec$imedi<0]<-0
table(ndidec$imedi)

ndidec$r2 <- ndidec$TRUR2
ndidec$r2[ndidec$r2<0]<-0
table(ndidec$r2)



ndidec$party <- factor(ndidec$party,
                        levels=c(1, 2, 3, 4, 5),
                        labels=c("GD", "UNM", "DKRA", "None", "Other"))


```

```{r}
table(ndidec$party, ndidec$SETTYPE)
prop.table(table(ndidec$party, ndidec$SETTYPE), 1)
prop.table(xtabs(WTIND~party+SETTYPE, data=ndidec), 1)
prop.table(xtabs(WTIND~party, data=ndidec, na.action = "na.omit"))
prop.table(xtabs(WTIND~r2+imedi, data=ndidec, na.action = "na.omit"), 1)
prop.table(xtabs(WTIND~party+r2, data=ndidec, na.action = "na.omit"), 1)

```

